name: AppImage

on:
  push:
    branches: [ master, appimage ]
  pull_request:
    branches: [ master ]

jobs:
  build-appimage:
    runs-on: ubuntu-latest

    steps:
      - name: "Clone w/ submodules"
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Install missing packages
        run: sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
      - name: Configure
        run: cmake -S . -B ~/buildag -DCMAKE_CXX_COMPILER=g++-10 --install-prefix ~/AppDir
      - name: Build
        run: cmake --build ~/buildag -j 4
      - name: Install
        run: cmake --install ~/buildag
      - name: AppImage
        run: sh ./scripts/appimage.sh
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'

